//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Kdl {

public class ChainFkSolverVel : SolverI {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ChainFkSolverVel(global::System.IntPtr cPtr, bool cMemoryOwn) : base(kdlPINVOKE.ChainFkSolverVel_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChainFkSolverVel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          kdlPINVOKE.delete_ChainFkSolverVel(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual int JntToCart(JntArrayVel q_in, FrameVel _out, int segmentNr) {
    int ret = kdlPINVOKE.ChainFkSolverVel_JntToCart__SWIG_0(swigCPtr, JntArrayVel.getCPtr(q_in), FrameVel.getCPtr(_out), segmentNr);
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int JntToCart(JntArrayVel q_in, FrameVel _out) {
    int ret = kdlPINVOKE.ChainFkSolverVel_JntToCart__SWIG_1(swigCPtr, JntArrayVel.getCPtr(q_in), FrameVel.getCPtr(_out));
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int JntToCart(JntArrayVel q_in, FrameVelVector _out, int segmentNr) {
    int ret = kdlPINVOKE.ChainFkSolverVel_JntToCart__SWIG_2(swigCPtr, JntArrayVel.getCPtr(q_in), FrameVelVector.getCPtr(_out), segmentNr);
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int JntToCart(JntArrayVel q_in, FrameVelVector _out) {
    int ret = kdlPINVOKE.ChainFkSolverVel_JntToCart__SWIG_3(swigCPtr, JntArrayVel.getCPtr(q_in), FrameVelVector.getCPtr(_out));
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void updateInternalDataStructures() {
    kdlPINVOKE.ChainFkSolverVel_updateInternalDataStructures(swigCPtr);
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
