//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Kdl {

public class ChainIkSolverAcc : SolverI {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ChainIkSolverAcc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(kdlPINVOKE.ChainIkSolverAcc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChainIkSolverAcc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ChainIkSolverAcc obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          kdlPINVOKE.delete_ChainIkSolverAcc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual int CartToJnt(JntArray q_in, JntArray qdot_in, Twist a_in, JntArray qdotdot_out) {
    int ret = kdlPINVOKE.ChainIkSolverAcc_CartToJnt__SWIG_0(swigCPtr, JntArray.getCPtr(q_in), JntArray.getCPtr(qdot_in), Twist.getCPtr(a_in), JntArray.getCPtr(qdotdot_out));
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int CartTojnt(JntArray q_init, FrameAcc a_in, JntArrayAcc q_out) {
    int ret = kdlPINVOKE.ChainIkSolverAcc_CartTojnt__SWIG_0(swigCPtr, JntArray.getCPtr(q_init), FrameAcc.getCPtr(a_in), JntArrayAcc.getCPtr(q_out));
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int CartToJnt(JntArray q_in, Twist v_in, Twist a_in, JntArray qdot_out, JntArray qdotdot_out) {
    int ret = kdlPINVOKE.ChainIkSolverAcc_CartToJnt__SWIG_1(swigCPtr, JntArray.getCPtr(q_in), Twist.getCPtr(v_in), Twist.getCPtr(a_in), JntArray.getCPtr(qdot_out), JntArray.getCPtr(qdotdot_out));
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int CartTojnt(JntArray q_init, Frame p_in, JntArray qdot_in, Twist a_in, JntArray q_out, JntArray qdotdot_out) {
    int ret = kdlPINVOKE.ChainIkSolverAcc_CartTojnt__SWIG_1(swigCPtr, JntArray.getCPtr(q_init), Frame.getCPtr(p_in), JntArray.getCPtr(qdot_in), Twist.getCPtr(a_in), JntArray.getCPtr(q_out), JntArray.getCPtr(qdotdot_out));
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void updateInternalDataStructures() {
    kdlPINVOKE.ChainIkSolverAcc_updateInternalDataStructures(swigCPtr);
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
