//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Kdl {

public class ChainJntToJacSolver : SolverI {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ChainJntToJacSolver(global::System.IntPtr cPtr, bool cMemoryOwn) : base(kdlPINVOKE.ChainJntToJacSolver_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChainJntToJacSolver obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          kdlPINVOKE.delete_ChainJntToJacSolver(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ChainJntToJacSolver(Chain chain) : this(kdlPINVOKE.new_ChainJntToJacSolver(Chain.getCPtr(chain)), true) {
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual int JntToJac(JntArray q_in, Jacobian jac, int segmentNR) {
    int ret = kdlPINVOKE.ChainJntToJacSolver_JntToJac__SWIG_0(swigCPtr, JntArray.getCPtr(q_in), Jacobian.getCPtr(jac), segmentNR);
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int JntToJac(JntArray q_in, Jacobian jac) {
    int ret = kdlPINVOKE.ChainJntToJacSolver_JntToJac__SWIG_1(swigCPtr, JntArray.getCPtr(q_in), Jacobian.getCPtr(jac));
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int setLockedJoints(BoolVector locked_joints) {
    int ret = kdlPINVOKE.ChainJntToJacSolver_setLockedJoints(swigCPtr, BoolVector.getCPtr(locked_joints));
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void updateInternalDataStructures() {
    kdlPINVOKE.ChainJntToJacSolver_updateInternalDataStructures(swigCPtr);
    if (kdlPINVOKE.SWIGPendingException.Pending) throw kdlPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
